coverage:
  precision: 2
  round: down
  range: "70...100"

ignore:
  - "tests"
  - ".*/__init__\\.py"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

status:
  project: true
  patch: true
  changes: true
