"""Validate the repository knowledge map without runtime dependencies.

Check inline Markdown link paths, not anchors or external URL availability.
Use --write to refresh only the generated schema inventory.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import TypedDict, cast
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
GENERATED = "docs/generated/db-schema.md"
DIRECTORIES = (
    "docs/design-docs",
    "docs/exec-plans/active",
    "docs/exec-plans/completed",
    "docs/generated",
    "docs/product-specs",
    "docs/references",
)
REQUIRED = (
    "AGENTS.md",
    "CLAUDE.md",
    "ARCHITECTURE.md",
    "docs/design-docs/index.md",
    "docs/design-docs/core-beliefs.md",
    "docs/exec-plans/tech-debt-tracker.md",
    GENERATED,
    "docs/product-specs/index.md",
    "docs/product-specs/new-user-onboarding.md",
    "docs/references/index.md",
    "docs/references/design-system-reference-llms.txt",
    "docs/references/nixpacks-llms.txt",
    "docs/references/uv-llms.txt",
    "docs/DESIGN.md",
    "docs/FRONTEND.md",
    "docs/PLANS.md",
    "docs/PRODUCT_SENSE.md",
    "docs/QUALITY_SCORE.md",
    "docs/RELIABILITY.md",
    "docs/SECURITY.md",
    "docs/contributing.md",
)
SchemaDocument = TypedDict(
    "SchemaDocument",
    {"title": str, "properties": dict[str, object], "$defs": dict[str, object]},
    total=False,
)
LINK = re.compile(r"\[[^\]\n]+\]\(([^)\n]+)\)")


def render_inventory(root: Path) -> str:
    """Render schema metadata from committed JSON, without importing the SDKs."""
    lines = [
        "# Schema and storage inventory",
        "",
        "Generated by `make harness-generate`. Do not edit this file manually.",
        "",
        "HoloDeck has no central relational database schema or migration directory.",
        "This inventory lists published JSON contracts and links storage code.",
        "",
        "| Schema | Title | Root properties | Definitions |",
        "| --- | --- | --- | --- |",
    ]
    fingerprints = []
    for path in sorted((root / "schemas").glob("*.schema.json")):
        content = path.read_bytes()
        # The repository owns these JSON Schema documents. Narrow JSON at this edge.
        schema = cast(SchemaDocument, json.loads(content))
        lines.append(
            f"| [{path.name}](../../schemas/{path.name}) | "
            f"{schema.get('title', path.stem)} | "
            f"{len(schema.get('properties', {}))} | "
            f"{len(schema.get('$defs', {}))} |"
        )
        fingerprints.append(
            f"<!-- {path.name} sha256: {hashlib.sha256(content).hexdigest()} -->"
        )
    lines.extend(["", *fingerprints])
    lines.extend(
        [
            "",
            "## Storage implementations",
            "",
            "- [Evaluation writer](../../src/holodeck/lib/eval_run/writer.py): "
            "atomic JSON artifacts under `results/<agent-slug>/`.",
            "- [Deployment state](../../src/holodeck/deploy/state.py): "
            "`.holodeck/deployments.json` beside the agent configuration.",
            "- [Vector stores](../guides/vector-stores.md): "
            "configured embedding stores.",
            "- [Temporal](../guides/temporal.md): externally managed workflow history.",
            "",
            "The agent schema is generated from Pydantic and loader authoring keys.",
            "Run `make schema` before this inventory when those inputs change.",
            "The optimizer progress schema is a separately committed contract.",
            "",
        ]
    )
    return "\n".join(lines)


def local_links(path: Path) -> set[Path]:
    """Resolve inline local links outside fenced examples, excluding URL fragments."""
    targets: set[Path] = set()
    fence: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.lstrip()
        if stripped.startswith(("```", "~~~")):
            marker = stripped[:3]
            if fence is None:
                fence = marker
            elif marker == fence:
                fence = None
            continue
        if fence is not None:
            continue
        for raw in LINK.findall(line):
            destination = raw.split(' "', 1)[0].strip().strip("<>")
            url = urlsplit(destination)
            if url.scheme or url.netloc or not url.path:
                continue
            targets.add((path.parent / unquote(url.path)).resolve())
    return targets


def check(root: Path) -> list[str]:
    """Return actionable errors for missing, stale, or undiscoverable harness files."""
    root = root.resolve()
    errors = []
    for name in REQUIRED:
        if not (root / name).is_file():
            errors.append(f"{name}: missing harness document; restore it and its link.")
    for name in DIRECTORIES:
        if not (root / name).is_dir():
            errors.append(
                f"{name}: missing directory; retain empty plan dirs with .gitkeep."
            )
    if errors:
        return errors

    agents = (root / "AGENTS.md").read_text(encoding="utf-8")
    if len(agents.splitlines()) > 100:
        errors.append("AGENTS.md: exceeds 100 lines; move detail to a mapped document.")
    if (root / "CLAUDE.md").read_text(encoding="utf-8") != "@AGENTS.md\n":
        errors.append("CLAUDE.md: must contain only @AGENTS.md and a final newline.")
    if (root / GENERATED).read_text(encoding="utf-8") != render_inventory(root):
        errors.append(f"{GENERATED}: stale inventory; run make harness-generate.")

    documents = {root / name for name in REQUIRED if name != "CLAUDE.md"}
    for name in DIRECTORIES:
        documents.update((root / name).rglob("*.md"))
        documents.update((root / name).rglob("*.txt"))
    graph = {path: local_links(path) for path in documents}
    for path, targets in graph.items():
        for target in targets:
            if not target.is_relative_to(root) or not target.exists():
                errors.append(
                    f"{path.relative_to(root)}: broken local link to {target}; "
                    "fix the target or restore the file."
                )

    reachable: set[Path] = set()
    pending = [root / "AGENTS.md"]
    while pending:
        current = pending.pop()
        if current in reachable:
            continue
        reachable.add(current)
        pending.extend(graph.get(current, set()) & documents - reachable)
    for path in sorted(documents - reachable):
        errors.append(
            f"{path.relative_to(root)}: not reachable from AGENTS.md; "
            "link it from the relevant index."
        )
    return errors


def main() -> int:
    """Refresh the generated inventory on request, then validate the harness."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="refresh schema inventory")
    args = parser.parse_args()
    if args.write:
        (ROOT / GENERATED).parent.mkdir(parents=True, exist_ok=True)
        (ROOT / GENERATED).write_text(render_inventory(ROOT), encoding="utf-8")
    errors = check(ROOT)
    if errors:
        sys.stderr.write("\n".join(errors) + "\n")
        return 1
    sys.stdout.write(
        "Harness structure, links, discovery, and schema inventory passed.\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
